/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaylistRouteImport } from './routes/playlist'
import { Route as InstrumentRouteImport } from './routes/instrument'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as CatchRouteImport } from './routes/$catch'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistRoute = PlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentRoute = InstrumentRouteImport.update({
  id: '/instrument',
  path: '/instrument',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CatchRoute = CatchRouteImport.update({
  id: '/$catch',
  path: '/$catch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$catch': typeof CatchRoute
  '/analysis': typeof AnalysisRoute
  '/instrument': typeof InstrumentRoute
  '/playlist': typeof PlaylistRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$catch': typeof CatchRoute
  '/analysis': typeof AnalysisRoute
  '/instrument': typeof InstrumentRoute
  '/playlist': typeof PlaylistRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$catch': typeof CatchRoute
  '/analysis': typeof AnalysisRoute
  '/instrument': typeof InstrumentRoute
  '/playlist': typeof PlaylistRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$catch'
    | '/analysis'
    | '/instrument'
    | '/playlist'
    | '/settings'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$catch'
    | '/analysis'
    | '/instrument'
    | '/playlist'
    | '/settings'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/$catch'
    | '/analysis'
    | '/instrument'
    | '/playlist'
    | '/settings'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatchRoute: typeof CatchRoute
  AnalysisRoute: typeof AnalysisRoute
  InstrumentRoute: typeof InstrumentRoute
  PlaylistRoute: typeof PlaylistRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrument': {
      id: '/instrument'
      path: '/instrument'
      fullPath: '/instrument'
      preLoaderRoute: typeof InstrumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$catch': {
      id: '/$catch'
      path: '/$catch'
      fullPath: '/$catch'
      preLoaderRoute: typeof CatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatchRoute: CatchRoute,
  AnalysisRoute: AnalysisRoute,
  InstrumentRoute: InstrumentRoute,
  PlaylistRoute: PlaylistRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
